exports.INCREAMENT = "INCREAMENT";
exports.DECREAMENT = "DECREAMENT";

exports.ADD_WORD = "ADD_WORD";

exports.FETCH_USERS = "FETCH_USERS";
exports.FETCH_ERROR = "FETCH_ERROR";
exports.FETCH_SUCCESS = "FETCH_SUCCESS";
